### ISSUE TITLE
Windows executable crashes when generating rom file

### ISSUE THREAD

**Issue by jessetmia** [abyssonym/eternalnightmare#2]
Screen shot attached: https://gyazo.com/f5fc1342bd7c62cdf27f957b75100c85

The windows executable throws an exception whenever it attempts to generate the randomized flags (below). 

> Traceback (most recent call last):
  File "<string>", line 779, in <module>
  File "E:\roms\eternal-test\eternalnightmare\randomtools\interface.py", line 156, in run_interface
    o.full_randomize()
  File "E:\roms\eternal-test\eternalnightmare\randomtools\tablereader.py", line 493, in full_randomize
    % (cls, cls2))
Exception: Randomize order violated: <class '__main__.PortraitPaletteObject'> <class '__main__.PaletteObject'>
>

This only seems to happen when trying to generate custom flags instead of letting the system generate all flags. Please note that I pulled down the randomtools folder to see if that was the issue.

**Comment by 7Soul** [comment]
I get the exact same error when running the .py file, but it works if I don't set any flags

**Comment by abyssonym** [comment]
This should be resolved as of version 6.
